server:
  port: 8090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route vers le microservice PATIENTS (port 8081)
            - id: patient-service
              uri: http://localhost:8081
              predicates:
                - Path=/patients/**

            # Route vers le microservice NOTES (port 8082)
            - id: notes-service
              uri: http://localhost:8082
              predicates:
                - Path=/notes/**
