server:
  port: 8090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**

        - id: notes-service
          uri: http://localhost:8082
          predicates:
            - Path=/notes/**

        - id: risk-service
          uri: http://localhost:8083
          predicates:
            - Path=/risk/**
