server:
  port: 8090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:

        # PATIENT SERVICE
        - id: patientservice
          uri: http://patientservice:8081
          predicates:
            - Path=/patients/**

        # NOTES SERVICE
        - id: noteservice
          uri: http://noteservice:8082
          predicates:
            - Path=/notes/**

        # RISK SERVICE
        - id: riskservice
          uri: http://riskservice:8083
          predicates:
            - Path=/riskService/**
